articles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w-]+)/$', views.details, name='details'),
]

blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^(?P<year>[0-9]+)/$', views.year, name='year'),
    url(r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)$', views.month, name='month'),
    url(r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', views.day, name='day'),
    url(r'^tag/(?P<tag>[\w-]+)/$', views.tag, name='tag'),
]

core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.flatpages import views as flatpageviews
from blog import views as blogviews


# Include these two lines to use the core/admin.py file
admin.autodiscover()
import core.admin       # <-- this line *is* necessary

urlpatterns = [
    url(r'^$', blogviews.overview, name='index'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('login.urls', namespace='account')),

    # Own Apps
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^articles/', include('articles.urls', namespace='articles')),

    # Flatpages
    url(r'^papers/general-idea/$', flatpageviews.flatpage, {'url': '/papers/general-idea/'}, name='general-idea'),
    url(r'^ideas/integration-in-websites/$', flatpageviews.flatpage, {'url': '/ideas/integration-in-websites/'}, name='integration-in-websites'),
    url(r'^dev/dwarfjs/$', flatpageviews.flatpage, {'url': '/dev/discuss/'}, name='discuss'),
    url(r'^dev/ff-extension/$', flatpageviews.flatpage, {'url': '/dev/ff-extension/'}, name='ff-extension'),
    url(r'^definitions/$', flatpageviews.flatpage, {'url': '/definitions/'}, name='definitions'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from autoslug import AutoSlugField


class Article(models.Model):
    title = models.CharField('Title', max_length=50, blank=True)
    slug = AutoSlugField(null=True, populate_from='title')
    author = models.ForeignKey(User, null=True, blank=True, verbose_name="Author")
    content = models.TextField('Content', blank=False)
    created = models.DateTimeField('Created', default=datetime.now)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.CharField('Name', max_length=50, default="Anonym", blank=True)
    comment = models.TextField('Comment', max_length=1024, blank=False)
    created = models.DateTimeField('Created', default=datetime.now)
    article = models.ForeignKey(Article)

    def __str__(self):
        return self.comment

articles/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from articles.models import Article, Comment


def index(request):
    articles = get_list_or_404(Article.objects.order_by('-created'))
    return render(request, 'articles/list.html', {"articles": articles})


def details(request, slug):
    article = get_object_or_404(Article, slug=slug)
    comments = Comment.objects.filter(article=article)
    return render(request, 'articles/detail.html', {"article": article,
                                                    "comments": comments})

articles/templates/articles/detail.html
{% extends "base.html" %}
{% load markdown_deux_tags %}
{% load staticfiles %}

{% block heading %}
  <h1>{{ article.title }}</h1>
{% endblock %}

{% block content %}
  <script src="{% static 'assets/discuss/js/master.bundle.js' %}"></script>
  <link rel="stylesheet" href="{% static 'assets/discuss/css/discuss.css' %}">

  <p>
    {{ article.content|markdown }}
  </p>

  <p class="labbook-change text-muted">
    <a href="{% url 'admin:articles_article_change' article.id %}" class="text-muted">edit</a>
    <a href="{% url 'admin:articles_article_delete' article.id %}" class="text-muted">delete</a>
  </p>

  <hr>

  <section id="comments">
    <h3 data-toggle="collapse" data-target="#comments-list">
      <i class="fa fa-users"></i> Comments
    </h3>
    <div id='comments-list' class="collapse in">
      {% for comment in comments %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              {{ comment.author }} <small>{{ comment.created }}</small>
            </h3>
          </div>
          <div class="panel-body">
            {{ comment.comment|markdown }}
          </div>
        </div>
      {% empty %}
        <p>There are currently no comments.</p>
      {% endfor %}
      <p class="labbook-change text-muted">
        <a href="{% url 'admin:articles_comment_add' %}" class="text-muted">add</a>
      </p>
    </div>
  </section>
{% endblock %}

articles/templates/articles/list.html
{% extends "base.html" %}
{% load markdown_deux_tags %}

{% block heading %}
  <h1>Testing Articles</h1>
{% endblock %}

{% block content %}
  {% for article in articles %}
    <h3>
      <a href="{% url 'articles:details' slug=article.slug %}">
        {{ article.title }}
      </a>
      <small>{{ article.created }}</small>
    </h3>
    <p>
      {{ article.content|striptags|truncatewords:50 }}
    </p>
    <p>
      <a href="{% url 'articles:details' slug=article.slug %}">more</a>
    </p>

    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}

  <p class="labbook-change text-muted">
    <a href="{% url 'admin:articles_article_add' %}" class="text-muted">add</a>
  </p>
{% endblock %}