blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^(?P<year>[0-9]+)/$', views.year, name='year'),
    url(r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)$', views.month, name='month'),
    url(r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', views.day, name='day'),
    url(r'^tag/(?P<tag>[\w-]+)/$', views.tag, name='tag'),
]

core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.flatpages import views as flatpageviews
from blog import views as blogviews


# Include these two lines to use the core/admin.py file
admin.autodiscover()
import core.admin       # <-- this line *is* necessary

urlpatterns = [
    url(r'^$', blogviews.overview, name='index'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('login.urls', namespace='account')),

    # Own Apps
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^articles/', include('articles.urls', namespace='articles')),

    # Flatpages
    url(r'^papers/general-idea/$', flatpageviews.flatpage, {'url': '/papers/general-idea/'}, name='general-idea'),
    url(r'^ideas/integration-in-websites/$', flatpageviews.flatpage, {'url': '/ideas/integration-in-websites/'}, name='integration-in-websites'),
    url(r'^dev/dwarfjs/$', flatpageviews.flatpage, {'url': '/dev/discuss/'}, name='discuss'),
    url(r'^dev/ff-extension/$', flatpageviews.flatpage, {'url': '/dev/ff-extension/'}, name='ff-extension'),
    url(r'^definitions/$', flatpageviews.flatpage, {'url': '/definitions/'}, name='definitions'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Labbook</title>

    {% load staticfiles %}
    {% load flatpages %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="{% static 'assets/bootswatch/yeti.css' %}">

    <!-- Fontawesome CSS-->
    <link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.min.css' %}">

    <script src="{% static 'assets/jquery/jquery.min.js' %}"></script>

    <!-- Own Styles -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>

  <body role="document">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Labbook</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        {% if user.is_authenticated %}
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Thoughts <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'blog:year' year=2016 %}">2016</a></li>
                  <li><a href="{% url 'blog:year' year=2015 %}">2015</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ideas <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'integration-in-websites' %}">Integration in Websites</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Development <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'discuss' %}">discuss</a></li>
                  <li><a href="{% url 'ff-extension' %}">Firefox Extension</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Paper <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'general-idea' %}">General Idea</a></li>
                </ul>
              </li>
              <li><a href="{% url 'wiki:index' %}">Wiki</a></li>
              <li><a href="{% url 'articles:index' %}">Articles</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="http://stackoverflow.com/editing-help"><i class="fa fa-question-circle fa-lg"></i></a></li>
              <li><a href="https://github.com/n2o/labbook"><i class="fa fa-github fa-lg"></i></a></li>
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-cog fa-lg"></i></a></li>
              <!--<li><a href="/account">Login</a></li>
              <li><a href="/account/register">Registrieren</a></li>-->
            </ul>
          </div><!--/.nav-collapse -->
        {% endif %}
      </div>
    </nav>

    <div id="main">
      <div class="container">
        {% block heading %}{% endblock %}
      </div>

      <div class="container" role="main">
        {% block content %}{% endblock %}
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}

{% block heading %}{% endblock %}

{% block content %}{% endblock %}